# Task 1
Construir un programa que reciba como entrada una imagen cuadrada que represente un laberinto. Deberá dibujar en pantalla la solución al mismo. Deberá considerar las siguientes restricciones:
- Las dimensiones de entrada podrán variar entre ejecuciones (pero siempre será una imagen cuadrada)
- Las áreas blancas representan caminos libres
- Las áreas negras representan paredes sobre las cuales no se puede pasar
- Las áreas verdes representan la meta (goalTest positivos) (pueden ser varios)
- La área roja representa el punto de inicio (solo podrá haber uno)



## Task 1.1 Discretización de la imagen

In [5]:
from PIL import Image 
import numpy as np

def colorMatch(color, target, tolerance=30):
    return colorDistance(color, target) <= tolerance

def colorDistance(rgb1, rgb2):
    return sum((c1-c2) ** 2 for c1, c2 in zip(rgb1, rgb2))**0.5

def processImage(path):
    # convertir la imagen .png o .bmp a rgba
    image = Image.open(path)
    image = image.convert('RGBA')

    # construir una matriz con ceros (en blanco) del tamaño de la imagen
    rows, columns = image.size
    matrix = np.zeros((rows, columns), dtype=np.int8)
    start = None
    goals = []

    # definir los colores

    blackC = (0, 0, 0, 255)
    whiteC = (255, 255, 255, 255)
    redC = (255, 0, 0, 255)
    greenC = (0, 255, 0, 255)
    
    for x in range(rows):
        for y in range(columns):
            red, green, black, a = image.getpixel((x, y))
            pixel_color = (red, green, black)
            
            # identificar límites
            if colorMatch(pixel_color, blackC): 
                matrix[x, y] = 1
            
            # Identificar el punto de inicio
            elif colorMatch(pixel_color, redC, tolerance=30):
                start = (x, y)
            
            # Identificar los puntos a alcanzar 
            elif colorMatch(pixel_color, greenC, tolerance=30):
                goals.append((x, y))

    return matrix, start, goals

matrix, start, goals = processImage("Test.bmp")
print(matrix)
print(start)
print(goals)

[[0 0 0 ... 0 0 0]
 [0 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 0]
 ...
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 0]
 [1 1 1 ... 1 1 0]]
None
[(79, 214), (79, 223), (80, 213), (80, 218), (80, 219), (81, 213), (81, 218), (81, 219), (84, 211), (84, 215), (84, 216), (84, 221), (84, 222), (84, 226), (85, 212), (85, 213), (85, 217), (85, 218), (85, 219), (85, 220), (85, 224), (85, 225), (86, 211), (86, 226), (89, 214), (89, 223), (90, 214), (90, 217), (90, 220), (90, 223), (91, 214), (91, 218), (91, 219), (91, 223), (92, 215), (92, 222), (476, 77), (476, 78), (476, 79), (476, 80), (477, 73), (477, 74), (478, 72), (478, 73), (478, 74), (479, 71), (479, 72), (479, 81), (480, 76), (480, 77), (480, 84), (481, 75), (481, 76), (481, 77), (482, 69), (482, 74), (482, 75), (482, 85), (483, 75), (483, 85), (485, 85), (486, 71), (487, 71), (488, 71), (490, 72), (492, 77), (492, 78), (492, 79)]


## Task 1.2 Framework de Problemas
Usar interfaz genérica o abstracta que sirva para representar el framework para definir el problema formal. Se debe utilizar la matriz obtenida del Task 1.1 y con esta deberá deducir las demás funciones del framework. (actions(s), stepCost(s,a,s), etc). Debe utilizar efectivamente los conceptos del paradigma POO. 

## Task 1.3 Graph-Search 
Construir el algoritmo genérico (familia de graphSearch). Este recibirá de parámetro una instancia del framework de problemas. Implemente los siguientes algoritmos:
- Breadth First Search (BFS)
- Depth First Search (DFS)
- A* (escoger dos heurísticas, justificar elección)

## TASK 1.3
### Breadth First Search (BFS)

## TASK 1.3
### Depth First Search (DFS)

## TASK 1.3
### A* 

In [ ]:
# Incluir ambas heurísticas aquí

## TASK 1.4
Resolver el laberinto de entrada y mostrar en pantalla gráficamente el camino encontrado. **Su representación se basará en la matriz discreta, no en la imagen original.**  